package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModule.SteerRequestType;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.signals.NeutralModeValue;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathPlannerPath;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.path.DynamicPathFactory;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during robot-centric path following. */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds =
        new SwerveRequest.ApplyRobotSpeeds()
            .withDriveRequestType(DriveRequestType.Velocity)
            .withSteerRequestType(SteerRequestType.Position);
    private final SwerveRequest.RobotCentric m_safeCoastRequest =
        new SwerveRequest.RobotCentric()
            .withDriveRequestType(DriveRequestType.Velocity)
            .withSteerRequestType(SteerRequestType.Position);
    private final SwerveRequest.SwerveDriveBrake m_brakeRequest =
        new SwerveRequest.SwerveDriveBrake()
            .withDriveRequestType(DriveRequestType.Velocity)
            .withSteerRequestType(SteerRequestType.Position);
    private final SwerveRequest.Idle m_idleRequest = new SwerveRequest.Idle();
    private double m_somAngleDiff = 0.0;
    private boolean m_autoShooting = false;
    private double m_autoRotDeg = 0.0;
    private int m_dynamicPathFailureCount = 0;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    public void updateDriverPerspective() {
        DriverStation.getAlliance().ifPresent(allianceColor -> {
            setOperatorPerspectiveForward(
                allianceColor == Alliance.Red
                    ? kRedAlliancePerspectiveRotation
                    : kBlueAlliancePerspectiveRotation
            );
            m_hasAppliedOperatorPerspective = true;
        });
    }

    public void setSafeCoastWithCurrentSpeeds() {
        ChassisSpeeds speeds = getState().Speeds;
        setControl(
            m_safeCoastRequest
                .withVelocityX(speeds.vxMetersPerSecond)
                .withVelocityY(speeds.vyMetersPerSecond)
                .withRotationalRate(speeds.omegaRadiansPerSecond)
        );
    }

    public void setBrakeRequest() {
        setControl(m_brakeRequest);
    }

    public void setIdleRequest() {
        setControl(m_idleRequest);
    }

    public void setDriveCoastNeutralMode() {
        setDriveNeutralMode(NeutralModeValue.Coast);
    }

    public void setDriveBrakeNeutralMode() {
        setDriveNeutralMode(NeutralModeValue.Brake);
    }

    public Command setDriveCoastNeutralModeCommand() {
        return runOnce(this::setDriveCoastNeutralMode)
                .withName("SetDriveCoastNeutralMode")
                .ignoringDisable(true);
    }

    public Command setDriveBrakeNeutralModeCommand() {
        return runOnce(this::setDriveBrakeNeutralMode)
                .withName("SetDriveBrakeNeutralMode")
                .ignoringDisable(true);
    }

    public Translation2d getHubPosition() {
        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        if (alliance == Alliance.Red) {
            return new Translation2d(
                Constants.DriveAimingConstants.redHubXMeters,
                Constants.DriveAimingConstants.redHubYMeters
            );
        }
        return new Translation2d(
            Constants.DriveAimingConstants.blueHubXMeters,
            Constants.DriveAimingConstants.blueHubYMeters
        );
    }

    public double getDistanceToHub() {
        Pose2d robotPose = getState().Pose;
        return robotPose.getTranslation().getDistance(getHubPosition());
    }

    public void setSomAngleDiff(double angleDiffDeg) {
        m_somAngleDiff = angleDiffDeg;
    }

    public double getSomAngleDiff() {
        return m_somAngleDiff;
    }

    public void setAutoShooting(boolean autoShooting) {
        m_autoShooting = autoShooting;
    }

    public boolean isAutoShooting() {
        return m_autoShooting;
    }

    public void setAutoRotDeg(double autoRotDeg) {
        m_autoRotDeg = autoRotDeg;
    }

    public double getAutoRotDeg() {
        return m_autoRotDeg;
    }

    public Optional<PathPlannerPath> generatePath(Pose2d targetPose) {
        return DynamicPathFactory.createStraightPath(getState().Pose, targetPose);
    }

    public Optional<PathPlannerPath> generateAutoPath(
            Pose2d targetPose,
            double maxSpeedMetersPerSecond,
            double maxAccelerationMetersPerSecondSquared) {
        return DynamicPathFactory.createAutoStraightPath(
                getState().Pose,
                targetPose,
                maxSpeedMetersPerSecond,
                maxAccelerationMetersPerSecondSquared);
    }

    public Optional<PathPlannerPath> generatePath(List<Pose2d> targetPoses) {
        return DynamicPathFactory.createMultiPointPath(getState().Pose, targetPoses);
    }

    public Optional<PathPlannerPath> generateShootOnMovePath(List<Pose2d> targetPoses) {
        return DynamicPathFactory.createShootOnMovePath(
                getState().Pose,
                getState().Speeds,
                targetPoses);
    }

    public Command followPathCommand(Pose2d targetPose) {
        return followGeneratedPath(
                () -> generatePath(targetPose),
                "single-target");
    }

    public Command autoFollowPathCommand(
            Pose2d targetPose,
            double maxSpeedMetersPerSecond,
            double maxAccelerationMetersPerSecondSquared) {
        return followGeneratedPath(
                () -> generateAutoPath(
                        targetPose,
                        maxSpeedMetersPerSecond,
                        maxAccelerationMetersPerSecondSquared),
                "auto-single-target");
    }

    public Command followPathCommand(List<Pose2d> targetPoses) {
        List<Pose2d> targets = targetPoses == null ? null : List.copyOf(targetPoses);
        return followGeneratedPath(
                () -> generatePath(targets),
                "multi-target");
    }

    public Command followShootOnMovePathCommand(double directionDegrees) {
        return followGeneratedPath(
                () -> generateShootOnMovePath(
                        DynamicPathFactory.createShootOnMoveTargets(
                                getState().Pose,
                                getHubPosition(),
                                directionDegrees)),
                "shoot-on-move");
    }

    private Command followGeneratedPath(
            Supplier<Optional<PathPlannerPath>> pathSupplier,
            String pathType) {
        return Commands.defer(
                () -> {
                    Optional<PathPlannerPath> path;
                    try {
                        path = pathSupplier.get();
                    } catch (RuntimeException ex) {
                        reportDynamicPathFailure(pathType, ex.getMessage());
                        return Commands.runOnce(this::setIdleRequest, this);
                    }

                    if (path.isEmpty()) {
                        reportDynamicPathFailure(pathType, "invalid or too-close target");
                        return Commands.runOnce(this::setIdleRequest, this);
                    }
                    if (!AutoBuilder.isConfigured()) {
                        reportDynamicPathFailure(pathType, "AutoBuilder is not configured");
                        return Commands.runOnce(this::setIdleRequest, this);
                    }

                    try {
                        return AutoBuilder.followPath(path.get())
                                .finallyDo(interrupted -> setIdleRequest());
                    } catch (RuntimeException ex) {
                        reportDynamicPathFailure(pathType, ex.getMessage());
                        return Commands.runOnce(this::setIdleRequest, this);
                    }
                },
                Set.of(this));
    }

    private void reportDynamicPathFailure(String pathType, String reason) {
        m_dynamicPathFailureCount++;
        SmartDashboard.putNumber("Path/DynamicFailureCount", m_dynamicPathFailureCount);
        SmartDashboard.putString("Path/DynamicLastFailure", pathType + ": " + reason);
        DriverStation.reportWarning(
                "Dynamic path fallback (" + pathType + "): " + reason,
                false);
    }

    private void setDriveNeutralMode(NeutralModeValue neutralMode) {
        Thread configThread = new Thread(() -> {
            StatusCode status = StatusCode.StatusCodeNotInitialized;
            for (int attempt = 0; attempt < 3; attempt++) {
                status = configNeutralMode(neutralMode);
                if (status.isOK()) {
                    SmartDashboard.putString(
                            "Drive/NeutralMode",
                            neutralMode.toString());
                    return;
                }
            }
            SmartDashboard.putString(
                    "Drive/NeutralModeFailure",
                    neutralMode + ": " + status);
            DriverStation.reportWarning(
                    "Failed to set swerve drive neutral mode to "
                            + neutralMode
                            + ": "
                            + status,
                    false);
        }, "SwerveNeutralModeConfig");
        configThread.setDaemon(true);
        configThread.start();
    }

    private void configureAutoBuilder() {
        try {
            RobotConfig config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,
                this::resetPose,
                () -> getState().Speeds,
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds
                        .withSpeeds(ChassisSpeeds.discretize(speeds, 0.02))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesX())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesY())
                ),
                new PPHolonomicDriveController(
                    new PIDConstants(5.0, 0.0, 0.0),
                    new PIDConstants(8.0, 0.0, 0.0)
                ),
                config,
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this
            );
        } catch (Exception ex) {
            DriverStation.reportError(
                "PathPlanner AutoBuilder configuration failed: " + ex.getMessage(),
                ex.getStackTrace()
            );
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
